version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/example-app
    ports:
      - "3000:3000"
    depends_on:
      - db
