default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: root
  pool: 5

development:
  <<: *default
  database: example_app_development

test:
  <<: *default
  database: example_app_test
